@extends('kol.layouts.app')

@section('title', 'Dashboard KOL')
@section('page-title', 'Dashboard saya')

@section('content')
    <div class="mb-8"><p class="text-sm text-slate-500">Selamat datang kembali, {{ $profile->nickname ?: $profile->user->name }}.</p><h2 class="mt-1 text-2xl font-bold tracking-tight text-slate-950">Siap membuka peluang baru?</h2></div>
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><x-dashboard.stat-card label="Endorsement aktif" :value="number_format($stats['activeEndorsements'])" icon="bi-briefcase" hint="Sedang berjalan" accent="indigo"/><x-dashboard.stat-card label="Komisi bulan ini" :value="'Rp'.number_format($stats['monthCommission'], 0, ',', '.')" icon="bi-cash-stack" hint="Total komisi" accent="emerald"/><x-dashboard.stat-card label="Tugas pending" :value="number_format($stats['pendingTasks'])" icon="bi-list-check" hint="Perlu diselesaikan" accent="amber"/><x-dashboard.stat-card label="Notifikasi" :value="number_format($stats['unreadNotifications'])" icon="bi-bell" hint="Belum dibaca" accent="rose"/></div>
    <div class="mt-6 grid gap-6 xl:grid-cols-[1.2fr_1fr]"><section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between p-5"><div><h3 class="font-bold text-slate-950">Endorsement terbaru</h3><p class="mt-1 text-sm text-slate-500">Progress pekerjaanmu</p></div><a href="#" class="text-xs font-semibold text-indigo-600">Lihat semua</a></div>@if ($recentEndorsements->isEmpty())<div class="flex h-52 items-center justify-center text-center text-sm text-slate-400"><p><i class="bi bi-briefcase mb-2 block text-2xl"></i>Belum ada endorsement.</p></div>@else<div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-y border-slate-100 bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr><th class="px-5 py-3 font-semibold">Campaign</th><th class="px-5 py-3 font-semibold">Deadline</th><th class="px-5 py-3 font-semibold">Status</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach ($recentEndorsements as $endorsement)<tr><td class="px-5 py-3"><p class="font-semibold text-slate-800">{{ $endorsement->campaign->name }}</p><p class="text-xs text-slate-400">{{ $endorsement->campaign->brand->name }}</p></td><td class="whitespace-nowrap px-5 py-3 text-slate-500">{{ $endorsement->deadline->format('d M Y') }}</td><td class="px-5 py-3"><x-dashboard.status-badge :status="$endorsement->status"/></td></tr>@endforeach</tbody></table></div>@endif</section><section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between p-5"><div><h3 class="font-bold text-slate-950">Jadwal mendatang</h3><p class="mt-1 text-sm text-slate-500">Agenda kolaborasi</p></div><a href="#" class="text-xs font-semibold text-indigo-600">Kalender</a></div>@if ($upcomingEndorsements->isEmpty())<div class="flex h-52 items-center justify-center text-center text-sm text-slate-400"><p><i class="bi bi-calendar3 mb-2 block text-2xl"></i>Belum ada jadwal mendatang.</p></div>@else<div class="space-y-3 px-5 pb-5">@foreach ($upcomingEndorsements as $endorsement)<div class="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><div class="flex size-10 shrink-0 flex-col items-center justify-center rounded-lg bg-indigo-50 text-indigo-600"><span class="text-sm font-bold leading-none">{{ $endorsement->deadline->format('d') }}</span><span class="mt-1 text-[9px] font-bold uppercase">{{ $endorsement->deadline->format('M') }}</span></div><div class="min-w-0"><p class="truncate text-sm font-semibold text-slate-800">{{ $endorsement->campaign->name }}</p><p class="mt-1 text-xs text-slate-400">{{ $endorsement->campaign->brand->name }} · {{ str($endorsement->content_type)->replace('_', ' ')->title() }}</p></div></div>@endforeach</div>@endif</section></div>
    <div class="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><div><h3 class="font-bold text-slate-950">Notifikasi terbaru</h3><p class="mt-1 text-sm text-slate-500">Informasi penting untukmu</p></div><a href="#" class="text-xs font-semibold text-indigo-600">Lihat semua</a></div>@if ($notifications->isEmpty())<div class="flex h-28 items-center justify-center text-center text-sm text-slate-400"><p><i class="bi bi-bell-slash mb-2 block text-2xl"></i>Belum ada notifikasi.</p></div>@else<div class="mt-5 grid gap-3 md:grid-cols-3">@foreach ($notifications as $notification)<div class="rounded-xl bg-slate-50 p-4"><div class="flex items-start gap-3"><i class="bi bi-bell text-amber-500"></i><div><p class="text-sm font-semibold text-slate-800">{{ $notification->title }}</p><p class="mt-1 text-xs leading-5 text-slate-500">{{ $notification->body }}</p></div></div></div>@endforeach</div>@endif</div>
@endsection
