<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Database\Factories\UserFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;

class User extends Authenticatable
{
    /** @use HasFactory<UserFactory> */
    use HasFactory, Notifiable;

    /**
     * The model's default values for attributes.
     *
     * @var array<string, mixed>
     */
    protected $attributes = [
        'is_active' => true,
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'is_active',
        'last_login_at',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
            'is_active' => 'boolean',
            'last_login_at' => 'datetime',
        ];
    }

    /**
     * The roles assigned to the user.
     */
    public function roles(): BelongsToMany
    {
        return $this->belongsToMany(Role::class, 'user_roles');
    }

    /**
     * The KOL profile associated with the user.
     */
    public function kolProfile(): HasOne
    {
        return $this->hasOne(KolProfile::class);
    }

    /**
     * Notifications for the user.
     */
    public function notifications(): HasMany
    {
        return $this->hasMany(Notification::class);
    }

    public function unreadNotifications(): HasMany
    {
        return $this->hasMany(Notification::class)->where('is_read', false);
    }

    /**
     * Audit logs generated by the user.
     */
    public function auditLogs(): HasMany
    {
        return $this->hasMany(AuditLog::class);
    }

    /**
     * Check if user has a specific role.
     */
    public function hasRole(string $roleName): bool
    {
        return $this->roles()->where('name', $roleName)->exists();
    }

    /**
     * Check if user is Superadmin / Admin.
     */
    public function isSuperadmin(): bool
    {
        return $this->hasRole('superadmin') || $this->hasRole('admin');
    }

    public function isAdmin(): bool
    {
        return $this->isSuperadmin();
    }

    /**
     * Check if user is KOL.
     */
    public function isKol(): bool
    {
        return $this->hasRole('kol');
    }

    /**
     * Check if user is Brand.
     */
    public function isBrand(): bool
    {
        return $this->hasRole('brand');
    }

    /**
     * The Brand profile associated with the user.
     */
    public function brand(): HasOne
    {
        return $this->hasOne(Brand::class);
    }

    /**
     * Assign role to user.
     */
    public function assignRole(string|Role $role): void
    {
        if (is_string($role)) {
            $roleModel = Role::firstOrCreate(
                ['name' => $role],
                ['display_name' => ucfirst($role)]
            );
            $this->roles()->syncWithoutDetaching([$roleModel->id]);
        } else {
            $this->roles()->syncWithoutDetaching([$role->id]);
        }
    }

    /**
     * Revoke all server-side sessions belonging to this user.
     */
    public function revokeSessions(): void
    {
        try {
            DB::table(config('session.table', 'sessions'))
                ->where('user_id', $this->getKey())
                ->delete();
        } catch (\Throwable) {
            // Ignore if session table does not exist or driver is not database
        }
    }
}
